
export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const GOOGLE_AUTH_START = 'GOOGLE_AUTH_START'
export const GOOGLE_AUTH_SUCCESS = 'GOOGLE_AUTH_SUCCESS'
export const GOOGLE_AUTH_FAILED = 'GOOGLE_AUTH_FAILED'

export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE'